In [1]:
!pip install -U sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 3.1 MB/s eta 0:00:00
  Using cached tqdm-4.66.4-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 402.6/402.6 kB 7.4 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 MB 2.4 MB/s eta 0:00:0000:0100:01
Using cached tqdm-4.66.4-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 4.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 3.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.3/30.3 MB 3.8 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.9/176.9 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 301.8/

In [2]:
!apt-get install mecab mecab-ipadic-utf8 python-mecab libmecab-dev
!pip install mecab-python3

/bin/bash: apt-get: command not found
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 5.9 MB/s eta 0:00:00a 0:00:01


In [10]:
!pip install fugashi

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 513.1/513.1 kB 8.3 MB/s eta 0:00:00a 0:00:01


In [3]:
!pip install ginza

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.4/109.4 kB 4.7 MB/s eta 0:00:00
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
  Using cached pydantic_core-2.18.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.5 kB)
  Using cached numpy-1.26.4-cp311-cp311-macosx_11_0_arm64.whl.metadata (114 kB)
  Using cached wrapt-1.16.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 6.0 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 MB 6.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 7.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.0/182.0 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.8/128.8 kB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.0/409.0 kB 6.3 MB/s eta 0:00:00a 0:00:01
Using cached 

In [12]:
!pip install fugashi ipadic

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 5.7 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for ipadic: filename=ipadic-1.0.0-py3-none-any.whl size=13556703 sha256=4394ad2490c24f9fb9fba7cb7b254c980f87c8145ddab409e43c8198d2fc449a
  Stored in directory: /Users/abetaichi/Library/Caches/pip/wheels/44/56/37/f543963822b85260c9f948df8fac8c20169c80dc71b24dc407
Successfully built ipadic


In [21]:
import pandas as pd
df = pd.read_csv("dataset_20240623_174106.csv")
df

search_title                    search_authors  \
0     A/Bテスト実践ガイド　真のデータドリブンへ至る信用できる実験とは  Ron Kohavi，Diane Tang，Ya Xu，大杉直也   
1           AIエンジニアのための機械学習システムデザインパターン                              澁井雄介   
2    AI・データ分析プロジェクトのすべて[ビジネス力×技術力=価値創出]    大城信晃，マスクド・アナライズ，伊藤徹郎，小西哲平，西原成輝   
3                              AI白書2019           独立行政法人情報処理推進機構AI白書編集委員会   
4         AWS運用入門 押さえておきたいAWSの基本と運用ノウハウ                 佐竹陽一，山﨑翔平，小倉大，峯侑資   
..                                  ...                               ...   
385                                音声認識                              篠田浩一   
386                             高次元の統計学                          青嶋誠，矢田和善   
387           ＬａＴｅＸ超入門　ゼロからはじめる理系の文書作成術                              水谷正大   
388           ＬａＴｅＸ超入門　ゼロからはじめる理系の文書作成術                              水谷正大   
389               Ｐｙｔｈｏｎで学ぶアルゴリズムとデータ構造                          下平英寿，辻真吾   

    search_publisher                        title  \
0               ドワンゴ                  A/Bテスト実践ガイド   
1                翔泳社  AIエンジニアのための機械学習システムデザインパターン   
2              技術評論社           AI・データ分析プロジェクトのすべて   
3           KADOKAWA                          NaN   
4          SBクリエイティブ                      AWS運用入門   
..               ...                          ...   
385              講談社                         音声認識   
386             共立出版                      高次元の統計学   
387              講談社                     LaTeX超入門   
388              講談社                     LaTeX超入門   
389              講談社        Ｐｙｔｈｏｎで学ぶアルゴリズムとデータ構造   

                                      authors  publisher published_date  \
0               Ron Kohavi, Diane Tang, Ya Xu        NaN        2021-03   
1                                       澁井 雄介        翔泳社     2021-05-17   
2    大城信晃, マスクド・アナライズ, 伊藤徹郎, 小西哲平, 西原成輝, 油井志郎        NaN        2020-12   
3                                         NaN        NaN            NaN   
4                        佐竹陽一, 山﨑翔平, 小倉大, 峯侑資  SBクリエイティブ     2023-03-31   
..                                        ...        ...            ...   
385                                      篠田浩一        NaN        2017-12   
386                                 青嶋誠, 矢田和善        NaN     2019-04-30   
387                                      水谷正大        NaN        2020-07   
388                                      水谷正大        NaN        2020-07   
389                                 辻真吾, 下平英寿        講談社     2019-11-28   

                                           description  page_count categories  \
0               経営層からデータサイエンティスト、エンジニアまで全関係者必読の教科書!...       289.0        NaN   
1    機械学習システム構築に必要な デザインパターンがここにある！ 【本書の背景】 Pythonを...       442.0        NaN   
2    現場でしか得られないビジネス知識/暗黙知を解説。課題設定→案件獲得→外注見積→契約→分析手法...       320.0        NaN   
3                                                  NaN         NaN        NaN   
4    現場で役立つ！ AWSトップエンジニアが実践しているシステム運用の手法とコツ ※この電子書籍...       507.0  Computers   
..                                                 ...         ...        ...   
385  基礎理論はコンパクトにまとめ、「耐雑音」「話者認識」「深層学習」についてたっぷり解説。音声認...       165.0        NaN   
386                                                NaN       110.0        NaN   
387  理系のレポート作成や論文執筆の定番「LaTeX」の使い方が一冊でわかる!これだけ読めばレポー...       270.0        NaN   
388  理系のレポート作成や論文執筆の定番「LaTeX」の使い方が一冊でわかる!これだけ読めばレポー...       270.0        NaN   
389  現代社会を支える根幹技術をPythonで！ Pythonプログラミングのスキルアップにも最適...       268.0  Computers   

    language                                          thumbnail  use_title  \
0         ja  http://books.google.com/books/content?id=EyRjz...        1.0   
1         ja  http://books.google.com/books/content?id=88ArE...        1.0   
2         ja  http://books.google.com/books/content?id=s4Idz...        1.0   
3        NaN                                                NaN        NaN   
4         ja  http://books.google.com/books/content?id=Dnm1E...        1.0   
..       ...                                                ...        ...   
385       ja  http://books.google.com/books/c

In [26]:
df["description"].fillna("記述なし").values.tolist()

['経営層からデータサイエンティスト、エンジニアまで全関係者必読の教科書!...',
 '機械学習システム構築に必要な デザインパターンがここにある！ 【本書の背景】 Pythonを用いた機械学習のモデル開発事例は多数ありますが、 そのモデルをビジネスやシステムに組み込み、運用する事例や方法論は多くありません。 そのため、AIを組み込んだ実装モデルをまとめた、 「機械学習システムのデザインパターン」に注目が集まっています。 【対象読者】 ・AIエンジニア ・システムエンジニア ・機械学習を本番システムとして使うための開発、運用方法で悩んでいるエンジニアの方 【本書の概要】 本書は機械学習を有効活用するためにはシステムに組み込むための設計や 実装が必要と考え、機械学習システムのデザインパターンを集めて解説した書籍です。 機械学習システムのグランドデザインおよびPythonによる機械学習システムの実装例を説明しつつ、 機械学習を本番活用するための方法論や、運用、改善ノウハウについて解説します。 本書で扱うプラットフォームには、コードの再現実行を担保するため、 DockerとKubernetesを活用します。 機械学習の学習から評価、QAを行い、推論器をリリースして 運用するまでの一連の流れをアーキテクチャやコードとともに解説します。 【デザインパターンのサンプル】 本書で解説している実際のサンプルコードをGitHubからダウンロードして利用可能です。 【本書のゴール】 ・機械学習を実用化する方法が学べる ・Pythonによる機械学習ワークフローおよびWebアプリケーション開発の概要を学べる ・機械学習を組み込んだシステムの運用ノウハウを得られる ・機械学習システムのトラブルシューティングや調査方法を学べる 【著者プロフィール】 澁井 雄介（しぶい・ゆうすけ） 株式会社ティアフォー所属。 MLOpsエンジニア、インフラエンジニア、ARエンジニア、ネコ2匹の飼い主。家に猫用ハンモックが4台ある。 本業で自動運転のためのMLOps基盤をKubernetesで開発しつつ、趣味でARとEdge AIを組み合わせて遊んでいる。 過去にはSIer、外資ソフトウェアベンダー、スタートアップで新規プロダクトの起ち上げ、大規模システム運用、チームマネジメントに従事。 前職メルカリにて機械学

In [30]:
from sentence_transformers import SentenceTransformer, models
from sentence_transformers.models import Transformer, Pooling

transformer = Transformer('cl-tohoku/bert-base-japanese-whole-word-masking')
pooling = Pooling(transformer.get_word_embedding_dimension(), pooling_mode_mean_tokens=False, pooling_mode_cls_token=True, pooling_mode_max_tokens=False)
model = SentenceTransformer(modules=[transformer, pooling])

sentences = df["description"].fillna("記述なし").values.tolist()
embeddings = model.encode(sentences)
embeddings


/Users/abetaichi/master/app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


array([[ 0.28449714, -0.14825982,  0.08901754, ..., -0.583057  ,
        -0.0719334 , -0.16652516],
       [-0.2517601 , -0.09318337, -0.8791181 , ..., -0.19825548,
        -0.54661006, -0.03238581],
       [-0.6428728 ,  0.49908695, -0.08862256, ..., -0.35763887,
        -0.4635009 ,  0.19611615],
       ...,
       [-0.2744395 ,  0.16816276, -0.17471284, ..., -0.6563951 ,
        -0.08829963, -0.23920502],
       [-0.2744395 ,  0.16816276, -0.17471284, ..., -0.6563951 ,
        -0.08829963, -0.23920502],
       [-0.13540842, -0.1565875 , -0.3880207 , ..., -0.33481348,
        -0.29473698,  0.10787263]], dtype=float32)

In [31]:
embeddings.shape

(390, 768)

In [32]:
import numpy as np
from datetime import datetime

# 今日の日付を取得
today_date = datetime.today().strftime('%Y%m%d')

# embeddingsをnumpy形式で保存
file_name = f"embeddings_{today_date}.npy"
np.save(file_name, embeddings)

# 保存したファイルを確認
loaded_embeddings = np.load(file_name)
loaded_embeddings


array([[ 0.28449714, -0.14825982,  0.08901754, ..., -0.583057  ,
        -0.0719334 , -0.16652516],
       [-0.2517601 , -0.09318337, -0.8791181 , ..., -0.19825548,
        -0.54661006, -0.03238581],
       [-0.6428728 ,  0.49908695, -0.08862256, ..., -0.35763887,
        -0.4635009 ,  0.19611615],
       ...,
       [-0.2744395 ,  0.16816276, -0.17471284, ..., -0.6563951 ,
        -0.08829963, -0.23920502],
       [-0.2744395 ,  0.16816276, -0.17471284, ..., -0.6563951 ,
        -0.08829963, -0.23920502],
       [-0.13540842, -0.1565875 , -0.3880207 , ..., -0.33481348,
        -0.29473698,  0.10787263]], dtype=float32)

# 検索部分をテスト

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

# クエリの入力
query = "★数学とプログラミングを対比させながら、一歩一歩わかりやすく！ 実務に即してPyMC5プログラミングでベイズ推論を使いこなせるようになる。 最初の一冊として、データサイエンティストにおすすめ！ 【サポートサイト】 https://github.com/makaishi2/python_bayes_intro 【主な内容】 第1章 確率分布を理解する 1.1 ベイズ推論における確率分布の必要性 1.2 確率変数と確率分布 1.3 離散分布と連続分布 1.4 PyMCによる確率モデル定義とサンプリング 1.5 サンプリング結果分析 1.6 確率分布とPyMCプログラミングの関係 第2章 よく利用される確率分布 2.1 ベルヌーイ分布（pm.Bernoulliクラス） 2.2 二項分布（pm.Binomial クラス） 2.3 正規分布（pm.Normal クラス） 2.4 一様分布（pm.Uniform クラス） 2.5 ベータ分布（pm.Beta クラス） 2.6 半正規分布（pm.HalfNormal クラス） 第3章 ベイズ推論とは 3.1 ベイズ推論利用の目的 3.2 問題設定 3.3 最尤推定による解法 3.4 ベイズ推論による解法 3.5 ベイズ推論の精度を上げる方法 3.6 ベイズ推論の活用例 第4章 はじめてのベイズ推論実習 4.1 問題設定 (再掲) 4.2 最尤推定 4.3 ベイズ推論 (確率モデル定義） 4.4 ベイズ推論 (サンプリング） 4.5 ベイズ推論 (結果分析） 4.6 ベイズ推論 (二項分布バージョン） 4.7 ベイズ推論 (試行回数を増やす） 4.8 ベイズ推論 (事前分布の変更） 4.9 ベータ分布で直接確率分布を求める 第5章 ベイズ推論プログラミング 5.1 データ分布のベイズ推論 5.2 線形回帰のベイズ推論 5.3 階層ベイズモデル 5.4 潜在変数モデル 第6章 ベイズ推論の業務活用事例 6.1 ABテストの効果検証 6.2 ベイズ回帰モデルによる効果検証 6.3 IRT (Item Response Theory）によるテスト結果評価..."

# クエリのembeddingを計算
query_embedding = model.encode([query])

# コサイン類似度を計算
similarities = cosine_similarity(query_embedding, embeddings)[0]

# 類似度の上位n件のインデックスを取得
top_n = 5  # 取得する上位n件の数
top_indices = similarities.argsort()[-top_n:][::-1]
df.iloc[top_indices]

search_title search_authors search_publisher  \
46   Pythonでスラスラわかるベイズ推論「超」入門      赤石雅典，須山敦志              講談社   
244                      強化学習           森村哲郎              講談社   
176                   ベイズ深層学習           須山敦志              講談社   
44       Pythonではじめるベイズ機械学習入門  森賀新，木田悠歩，須山敦志              講談社   
78              これならわかる機械学習入門           富谷昭夫              講談社   

                         title          authors publisher published_date  \
46   Ｐｙｔｈｏｎでスラスラわかる　ベイズ推論「超」入門       赤石雅典, 須山敦志       講談社     2023-11-23   
244                       強化学習             森村哲郎       講談社     2019-05-23   
176                    ベイズ深層学習             須山敦志       講談社     2019-08-08   
44        Ｐｙｔｈｏｎではじめるベイズ機械学習入門  森賀新, 木田悠歩, 須山敦志       講談社     2022-05-26   
78               これならわかる機械学習入門             富谷昭夫       講談社     2021-03-29   

                                           description  page_count  \
46   ★数学とプログラミングを対比させながら、一歩一歩わかりやすく！ 実務に即してPyMC5プログ...       298.0   
244  理論は裏切らない！ ・強化学習で必要になる数理を広くカバーした。・一貫したていねいな解説なの...       381.0   
176  「読んでいて本当に心地がいい」と大好評の前著『ベイズ推論による機械学習入門』からの第２弾！ ...       314.0   
44   ★確率的プログラミング言語がすぐに使える！★ ・Pythonでのコーディングを前提に、PyM...       359.0   
78   【道具として使いこなす！】 膨大な観測データから普遍的な法則を抽出する手法とは？ 高校数学レ...       289.0   

                   categories language  \
46                  Computers       ja   
244  Technology & Engineering       ja   
176                 Computers       ja   
44                  Computers       ja   
78                Mathematics       ja   

                                             thumbnail  use_title  use_author  \
46   http://books.google.com/books/content?id=H5nlE...        1.0         1.0   
244  http://books.google.com/books/content?id=QmmuD...        1.0         1.0   
176  http://books.google.com/books/content?id=2360D...        1.0         1.0   
44   http://books.google.com/books/content?id=lfqLE...        1.0         1.0   
78   http://books.google.com/books/content?id=Yz81E...        1.0         1.0   

     use_publisher  errors  
46             1.0       0  
244            0.0       0  
176            1.0       0  
44             1.0       0  
78             1.0       0

In [37]:
embeddings

array([[ 0.28449714, -0.14825982,  0.08901754, ..., -0.583057  ,
        -0.0719334 , -0.16652516],
       [-0.2517601 , -0.09318337, -0.8791181 , ..., -0.19825548,
        -0.54661006, -0.03238581],
       [-0.6428728 ,  0.49908695, -0.08862256, ..., -0.35763887,
        -0.4635009 ,  0.19611615],
       ...,
       [-0.2744395 ,  0.16816276, -0.17471284, ..., -0.6563951 ,
        -0.08829963, -0.23920502],
       [-0.2744395 ,  0.16816276, -0.17471284, ..., -0.6563951 ,
        -0.08829963, -0.23920502],
       [-0.13540842, -0.1565875 , -0.3880207 , ..., -0.33481348,
        -0.29473698,  0.10787263]], dtype=float32)